name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-container:
    name: Build Docker Container image
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ariessurya/best-to-buy
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build the Docker image with secrets as build args
      run: | 
        docker build -t $DOCKER_IMAGE_NAME:latest .

    - name: Push the Docker image
      run: docker push $DOCKER_IMAGE_NAME:latest